version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"

  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-fpm
    env_file:
      - .env
    links:
      - mysql
      - memcached
    volumes:
      - ./:/var/www/html

  nginx:
    image: nginx:latest
    container_name: nginx
    env_file:
      - .env
    volumes:
      - ./:/var/www/html
      - ./docker-assets/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker-assets/nginx/fastcgi-php.conf:/etc/nginx/fastcgi-php.conf
    ports:
      - "80:80"
      - "443:443"
      - "8880:8880"
    expose:
      - "80"
      - "443"
      - "8880"
    links:
      - php-fpm
      - mysql
      - memcached
    depends_on:
      - php-fpm

  memcached:
    image: memcached:latest
    container_name: memcached
    ports:
      - "11211:11211"

volumes:
  mysql_data: