ARG BASE_IMAGE
# Use the DDEV web image as the base
FROM $BASE_IMAGE

RUN apt install -y libosmesa6-dev libglu1-mesa  libpng-dev libjpeg-dev libminizip-dev

ADD https://github.com/ldraw-org/ldview/releases/download/v4.6/ldview-linux-x86_64-osmesa-ldraw_library-4.6.tar.gz /tmp/
RUN tar -xzf /tmp/ldview-linux-x86_64-osmesa-ldraw_library-4.6.tar.gz -C /tmp \
    && install -D -m 755 /tmp/OSMesa/ldview /usr/bin/ldview \
    && rm /tmp/ldview-linux-x86_64-osmesa-ldraw_library-4.6.tar.gz
