<x-library-icon
    :icon="$icon"
    color="{{$iconColor}}"
    class="w-8"
    :lowerLeftIcon="$lowerLeftIcon"
    lowerLeftColor="{{$lowerLeftIconColor}}"
    :lowerRightIcon="$lowerRightIcon"
    lowerRightColor="{{$lowerRightIconColor}}"
/>
