<?php

namespace App\LDraw;

class LibraryConfig
{
    public static function partCategories(): array
    {
        return [
            ['category' => 'Animal'],
            ['category' => 'Antenna'],
            ['category' => 'Arch'],
            ['category' => 'Arm'],
            ['category' => 'Bar'],
            ['category' => 'Baseplate'],
            ['category' => 'Belville'],
            ['category' => 'Boat'],
            ['category' => 'Bracket'],
            ['category' => 'Brick'],
            ['category' => 'Car'],
            ['category' => 'Clikits'],
            ['category' => 'Cockpit'],
            ['category' => 'Cone'],
            ['category' => 'Constraction'],
            ['category' => 'Constraction Accessory'],
            ['category' => 'Container'],
            ['category' => 'Conveyor'],
            ['category' => 'Crane'],
            ['category' => 'Cylinder'],
            ['category' => 'Dish'],
            ['category' => 'Door'],
            ['category' => 'Duplo'],
            ['category' => 'Electric'],
            ['category' => 'Exhaust'],
            ['category' => 'Fence'],
            ['category' => 'Figure'],
            ['category' => 'Figure Accessory'],
            ['category' => 'Flag'],
            ['category' => 'Forklift'],
            ['category' => 'Freestyle'],
            ['category' => 'Garage'],
            ['category' => 'Glass'],
            ['category' => 'Grab'],
            ['category' => 'Helper'],
            ['category' => 'Hinge'],
            ['category' => 'Homemaker'],
            ['category' => 'Hose'],
            ['category' => 'Ladder'],
            ['category' => 'Lever'],
            ['category' => 'Magnet'],
            ['category' => 'Minifig'],
            ['category' => 'Minifig Accessory'],
            ['category' => 'Minifig Footwear'],
            ['category' => 'Minifig Headwear'],
            ['category' => 'Minifig Hipwear'],
            ['category' => 'Minifig Neckwear'],
            ['category' => 'Monorail'],
            ['category' => 'Moved'],
            ['category' => 'Obsolete'],
            ['category' => 'Panel'],
            ['category' => 'Plane'],
            ['category' => 'Plant'],
            ['category' => 'Plate'],
            ['category' => 'Platform'],
            ['category' => 'Pov-RAY'],
            ['category' => 'Propeller'],
            ['category' => 'Rack'],
            ['category' => 'Roadsign'],
            ['category' => 'Rock'],
            ['category' => 'Scala'],
            ['category' => 'Screw'],
            ['category' => 'Sheet Cardboard'],
            ['category' => 'Sheet Fabric'],
            ['category' => 'Sheet Plastic'],
            ['category' => 'Slope'],
            ['category' => 'Sphere'],
            ['category' => 'Staircase'],
            ['category' => 'Sticker'],
            ['category' => 'Sticker Shortcut'],
            ['category' => 'String'],
            ['category' => 'Support'],
            ['category' => 'Tail'],
            ['category' => 'Tap'],
            ['category' => 'Technic'],
            ['category' => 'Tile'],
            ['category' => 'Tipper'],
            ['category' => 'Tractor'],
            ['category' => 'Trailer'],
            ['category' => 'Train'],
            ['category' => 'Turntable'],
            ['category' => 'Tyre'],
            ['category' => 'Vehicle'],
            ['category' => 'Wedge'],
            ['category' => 'Wheel'],
            ['category' => 'Winch'],
            ['category' => 'Window'],
            ['category' => 'Windscreen'],
            ['category' => 'Wing'],
            ['category' => 'Znap'],
        ];
    }
}
